package com.checkout.payment.gateway.dto;

import com.checkout.payment.gateway.enums.PaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

public record PostPaymentResponse(
  @Schema(description = "Payment UUID generated by Payment GW", example = "228bf585-fda7-4bbc-84cc-d004cc203cc0")
  UUID id,
  @Schema(description = "Payment event status. Maps one to one with Bank statuses. Authorized/Declined/Rejected", example = "Authorized")
  PaymentStatus status,
  @Schema(description = "Card number last four digits", example = "4242")
  String cardNumberLastFour,
  @Schema(description = "Expiry month", example = "10")
  int expiryMonth,
  @Schema(description = "Expiry year", example = "2026")
  int expiryYear,
  @Schema(description = "Currency in ISO 3 digit format", example = "EUR")
  String currency,
  @Schema(description = "Amount in minor digits", example = "1000")
  int amount
) {
  @Override
  public String toString() {
    return "GetPaymentResponse{" +
        "id=" + id +
        ", status=" + status +
        ", cardNumberLastFour=" + cardNumberLastFour +
        ", expiryMonth=" + expiryMonth +
        ", expiryYear=" + expiryYear +
        ", currency='" + currency + '\'' +
        ", amount=" + amount +
        '}';
  }
}
